### PR TITLE
Possible improvements

### PR DESCRIPTION
**Pull request by frenchy64**
Thanks @jacekschae for this repo. I'm new to re-frame and it gave me a good idea of what it provides.

I found some possible inconsistencies which I tried to address in this PR.

1. `conduit.events/add-epoch`: I didn't understand how the `date` parameter was being used so I removed it, and the docstring seemed out of date.
2. `conduit.events/index-by`: Why did it pass `:createdAt` to `add-epoch`?
3. `:loading`: fixed `:loading` entries in events (they didn't always match up)
4. `:api-request-error`: more fixes for `:loading` updates, now takes an optional arg for the `:loading` key
5. Small style changes (avoid shadowing some `clojure.core` vars, use transducers, use `update` over `update-in`)
6. Fix `:disabled` usage in views

Please let me know which (if any) of these changes you're interested in, or if I've misunderstood something.

### CODE REVIEW

**Comment by frenchy64** [comment]
After sleeping on it, I feel I'm missing what `add-epoch` is supposed to do, and how `index-by` is supposed to use it. I'd welcome clarification.

**Comment by jacekschae** [comment]
Thanks for this PR! Didn't have a chance to look at the changes.

To clarify `add-epoch` it is converting dates to unix timestamps so that when we display the posts (the initially downloaded ones 10 or 20) they are displayed in order. `index-by` adds this prop when it converts `[]` to `{}` so later it's trivial to navigate. 

When we get the `blog posts` from the API one of the properties is - `:createdAt "2021-05-20T11:31:13.731Z"` and we use this information to add additional property `:epoch 1621510273731`. Then in the subscription we sort them by `:epoch` so they appear in order -- https://github.com/jacekschae/conduit/blob/732d56d5bd981bd47fab3cdd1b2d96ea27b1e7ff/src/conduit/subs.cljs#L14-L19

Take a look at the [re-frame-10x-demo](https://jacekschae.github.io/conduit-re-frame-10x-demo/). Press CTRL + h, if the re-frame 10x panel is not visible. There when you expand articles you will see `:epoch` along `:createdAt`. 

Screen Shot 2021-05-20 at 14 15 22

Hope that helps

**Comment by frenchy64** [comment]
Ah! Is this implementation correct? It makes `add-epoch` take an `item` and corrects (I think) the use of `.getTime`.


```clojure
(defn add-epoch
  "Add :epoch timestamp based on :createdAt field."
  [item]
  (assoc item :epoch (.getTime (:createdAt item))))

(defn index-by
  "Index collection by function f (usually a keyword) as a map"
  [f coll]
  (into {}
        (map (juxt f add-epoch))
        coll))
```


I added it to the PR when you can take a look. Thanks!

**Comment by jacekschae** [comment]
Thanks so much for this! Great updates across the board!

**Pull request merged**
